// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb7hpQX6bfaSY-Czxmn0nX0-M-y8BqFMI',
    appId: '1:507412831102:web:42ac3f8174a00170f7312f',
    messagingSenderId: '507412831102',
    projectId: 'restaurante-43f3a',
    authDomain: 'restaurante-43f3a.firebaseapp.com',
    storageBucket: 'restaurante-43f3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFdl7x3Psuj6bwj0JAZNiCNbgLOS0IUA0',
    appId: '1:507412831102:android:e1b536e07fd4cddef7312f',
    messagingSenderId: '507412831102',
    projectId: 'restaurante-43f3a',
    storageBucket: 'restaurante-43f3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEX9UO2o6ri9ZLIq1YdbJF_mqnMeRXViY',
    appId: '1:507412831102:ios:b0d40b215b89cd25f7312f',
    messagingSenderId: '507412831102',
    projectId: 'restaurante-43f3a',
    storageBucket: 'restaurante-43f3a.appspot.com',
    iosBundleId: 'com.example.appBrm01',
  );
}
